# Generated by Django 3.2.1 on 2021-05-06 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(5, 'Excellent'), (4, 'Very good'), (3, 'Good'), (2, 'Not bad'), (1, 'Bad')], default=1),
        ),
    ]
