# Generated by Django 3.2.1 on 2021-05-12 16:12

from django.db import migrations, models
import users.model


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=users.model.user_directory_path),
        ),
    ]
