# Generated by Django 3.2.1 on 2021-05-05 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_task', to=settings.AUTH_USER_MODEL, verbose_name='Автор заказа'),
        ),
        migrations.AddField(
            model_name='task',
            name='responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freelanse_task', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель заказа'),
        ),
    ]
