# Generated by Django 3.2.1 on 2021-05-10 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('close', 'Close'), ('progress', 'In progress'), ('planned', 'Planned')], default='open', max_length=10),
        ),
    ]
